experiment_name: hello-world-error-a10
environment:
  env_variables:
    NCCL_DEBUG: "INFO"
  dependencies: dependencies.yaml
compute:
  gpus: 2
  gpu_type: a10
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    allow_uncommitted: true
    repo_path: /Users/guanyu.chen/Documents/Projects/composer_geneformer_pretrain/
    include_paths:
      - SGC_hello_world_error_a10
command: |-
  echo ">>> Hello world error test (A10)"
  cd $CODE_SOURCE_PATH/SGC_hello_world_error_a10
  python train.py
