model_config:
  hidden_size: 256
  num_hidden_layers: 6
  initializer_range: 0.02
  layer_norm_eps: 1e-12
  attention_probs_dropout_prob: 0.02
  hidden_dropout_prob: 0.02
  intermediate_size: 512
  hidden_act: relu
  max_position_embeddings: 2048
  model_type: bert
  num_attention_heads: 4

fsdp_config:
  sharding_strategy: FULL_SHARD
  state_dict_type: sharded
  cpu_offload: False 
  mixed_precision: DEFAULT
  backward_prefetch: BACKWARD_POST
  activation_checkpointing: False
  activation_cpu_offload: False
  verbose: True

# Optimization
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur # Warmup to the full LR for 6% of the training duration
  alpha_f: 0.02 # Linearly decay to 0.02x the full LR by the end of the training duration

optimizer:
  name: decoupled_adamw
  lr: 5.0e-4 # Peak learning rate
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-5 # Amount of weight decay regularization

callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}

#make sure you have configured databricks secret
loggers:
  mlflow:
    tracking_uri: databricks
    experiment_name: /Users/srijit.nair@databricks.com/mlflow_experiments/geneformer_pretraining

device : gpu
seed_val : 42
run_name : geneformer_pretrain
working_dir : /pretrain/temp  

# Streaming Dataset
data_location : remote #local vs remote
local_data_dir : /Geneformer/data
data_bucket_name : srijit-nair-sandbox-bucket
data_bucket_key : geneformer/data
token_dictionary_filename : token_dictionary.pkl
streaming_dataset_location : streaming/genecorpus_30M_2048.dataset
mlm_probability: 0.15
# Batching
max_duration: 22ep
train_batch_size: 16
eval_batch_size: 16
device_train_microbatch_size : 16

train_subset_num_batches : 1000
eval_subset_num_batches : 100

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba
eval_interval: 2ep
#Checkpoint to remote object store
autoresume: False #loads from
reset_time: False
save_overwrite: True
save_interval: 5ep
save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
load_path: "dbfs:/databricks/mlflow-tracking/1513674964105587/61d1868a1a96472891653f9341925047/artifacts/ep20-ba20000/"
save_folder: "dbfs:/databricks/mlflow-tracking/{mlflow_experiment_id}/{mlflow_run_id}/artifacts/"
