name: multi-gpu-test
image: mosaicml/pytorch:2.2.2_cu121-python3.11-ubuntu20.04

integrations:
- integration_type: git_repo
  git_repo: srijitcn/composer_geneformer_pretrain
  git_branch: main # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  git clone https://huggingface.co/ctheodoris/Geneformer
  cd Geneformer
  pip install -e .

  cd ../composer_geneformer_pretrain
  mkdir data
  cd data
  curl https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/resolve/main/token_dictionary.pkl\?download\=true -o token_dictionary.pkl  

  cd ..
  pip install -r requirements.txt
  
  composer -n 8 train.py

compute:
  gpus: 8
  cluster: r8z11