name: geneformer-pretrain
image: mosaicml/pytorch:2.2.2_cu121-python3.11-ubuntu20.04
#image: mosaicml/composer:latest

integrations:
- integration_type: git_repo
  git_repo: srijitcn/composer_geneformer_pretrain
  git_branch: main # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  cd composer_geneformer_pretrain
  sh commands.sh
  echo ">>> Starting training"
  export MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=true
  composer train.py parameters.yaml

compute:
  gpus: 8
  cluster: r8z11

#enable watchdog
scheduling:
  retry_on_system_failure: True
  max_retries: 10