experiment_name: geneformer-pretrain
environment:
  env_variables:
    NCCL_DEBUG: "INFO"
  dependencies: dependencies.yaml
compute:
  gpus: 8
  gpu_type: h100
max_retries: 3
code_source:
  type: snapshot
  snapshot:
    repo_path: /Users/may.merkletan/Documents/Projects/Merck/composer_geneformer_pretrain_ref/composer_geneformer_pretrain/
command: |-
  cd $HOME/composer_geneformer_pretrain
  sh commands.sh
  echo ">>> Starting training"
  export MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING=true
  composer train.py parameters.yaml