name: multi-gpu-test
image: mosaicml/pytorch:2.2.2_cu121-python3.11-ubuntu20.04

integrations:
- integration_type: git_repo
  git_repo: srijitcn/composer_geneformer_pretrain
  git_branch: main # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  apt-get install git-lfs
  git clone https://huggingface.co/ctheodoris/Geneformer
  cd Geneformer
  git checkout b07f4b1e8893a0923a8fde223fe3b5a60b976d99
  pip install -e .

  cd ../composer_geneformer_pretrain
  mkdir output
  mkdir data
  cd data

  curl https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/resolve/main/token_dictionary.pkl\?download\=true -o token_dictionary.pkl  

  mkdir dataset
  cd dataset
  curl https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/raw/main/genecorpus_30M_2048.dataset/dataset.arrow -o dataset.arrow
  curl https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/raw/main/genecorpus_30M_2048.dataset/dataset_info.json -o dataset_info.json
  curl https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/raw/main/genecorpus_30M_2048.dataset/state.json -o state.json

  cd ../..
  pip install -r requirements.txt
  
  composer -n 8 train.py

compute:
  gpus: 8
  cluster: r8z11