name: multi-gpu-test
image: mosaicml/pytorch:2.2.2_cu121-python3.11-ubuntu20.04

integrations:
- integration_type: git_repo
  git_repo: srijitcn/composer_geneformer_pretrain
  git_branch: pyfunc # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  cd composer_geneformer_pretrain
  sh commands.sh
  echo ">>> Starting training"
  trap '/tmp/code tunnel unregister' EXIT
  cd /tmp && curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
  tar -xf vscode_cli.tar.gz
  /tmp/code tunnel --accept-server-license-terms --no-sleep --name mml-dev-01
  # composer -n 8 inference_full.py parameters.yaml

compute:
  gpus: 8
  cluster: r8z11
