experiment_name: hello-world-a10
environment:
  env_variables:
    NCCL_DEBUG: "INFO"
  dependencies: dependencies.yaml
compute:
  gpus: 2
  gpu_type: a10
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    allow_uncommitted: true
    repo_path: /Users/guanyu.chen/Documents/Projects/composer_geneformer_pretrain/
    include_paths:
      - SGC_hello_world_a10
command: |-
  echo ">>> Hello world A10 test"
  cd $CODE_SOURCE_PATH/SGC_hello_world_a10

  torchrun \
    --nnodes=1 \
    --nproc_per_node=2 \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    train_hello_world.py
