experiment_name: torchrun-hello-world
environment:
  env_variables:
    NCCL_DEBUG: "INFO"
  dependencies: dependencies.yaml
compute:
  gpus: 2
  gpu_type: a10
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    # repo_path is local path for your repo, and changes git commit is required for job submission
    repo_path: /Users/guanyu.chen/Documents/Projects/composer_geneformer_pretrain/
command: |-
  echo ">>> In SGC_hello_world folder, starting training"
  
  #Repo is in $HOME, so cd relative to $HOME
  cd $HOME/composer_geneformer_pretrain/SGC_hello_world
  
  torchrun \
    --nnodes=2 \
    --nproc_per_node=1 \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    train_hello_world.py
