experiment_name: torchrun-hello-world-guanyu
environment:
  env_variables:
    NCCL_DEBUG: "INFO"
  dependencies: dependencies.yaml
compute:
  gpus: 2
  gpu_type: a10
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    repo_path: /Users/may.merkletan/Documents/Projects/Merck/composer_geneformer_pretrain_ref/composer_geneformer_pretrain
command: |-

  # Path to the script inside the uploaded snapshot on the driver.
  TRAIN_SCRIPT="$HOME/composer_geneformer_pretrain/hello_world/train_guanyu.py"

  torchrun \
    --nnodes=1 \
    --nproc_per_node=2 \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --master_port=$MASTER_PORT \
    $TRAIN_SCRIPT
