experiment_name: merck-dep-test
env_variables:
    NCCL_DEBUG: "INFO"
environment:
  dependencies: dependencies.yaml
compute:
  gpus: 64
  gpu_type: H100
max_retries: 0
command: |-
  echo ">>> Starting dependency compatibility test"

  python /Workspace/Shared/test/sgc_cli/test_deps.py
