experiment_name: merck-dep-test
env_variables:
    NCCL_DEBUG: "INFO"
environment:
  dependencies: dependencies.yaml
compute:
  gpus: 64
  gpu_type: H100
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    repo_path: /Users/guanyu.chen/Documents/Projects/composer_geneformer_pretrain/
command: |-
  echo ">>> Starting dependency compatibility test"
  echo ">>> CODE_SOURCE_PATH=$HOME"

  cd $HOME/composer_geneformer_pretrain/SGC_merck_test
  python test_deps.py
