experiment_name: sgc-dep-test
# env_variables:
#     NCCL_DEBUG: "INFO"
environment:
  dependencies: dependencies.yaml
compute:
  gpus: 2
  gpu_type: A10
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    # allow_uncommitted: true
    repo_path: /Users/guanyu.chen/Documents/Projects/composer_geneformer_pretrain/SGC_dep_test
    # git_branch: test/dep-test
    # include_paths:
      # - SGC_dep_test
command: |-
  echo ">>> Upgrading transformers after streaming install"
  pip install "transformers>=5.0.0"

  echo ">>> Starting dependency compatibility test"
  echo ">>> CODE_SOURCE_PATH=$HOME"
  ls -la $HOME/SGC_dep_test/

  cd $HOME/SGC_dep_test
  python test_deps.py
